# Important: do not use in production environments
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aes-sample-portal
  namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aes-portal-config
  namespace: default
data:
   db_host: "my-redis.redis.svc.cluster.local"
   db_port: "6379"
   FLASK_RUN_PORT: "80"
---
apiVersion: v1
kind: Pod
metadata:
  name: aes-sample-portal
  namespace: default
  labels:
    app: aes-portal-deployment
spec:
  serviceAccountName: aes-sample-portal
  containers:
  - image: capzacr.azurecr.io/sample_portal:latest
    imagePullPolicy: Always
    name: aes-sample-portal
    envFrom:
      - configMapRef: {name: aes-portal-config}
    #command: ["sh", "-c"]
    #args: ["sleep infinity"]
    command: ["flask"]
    args: ["--app", "portal_app", "run", "--host",  "0.0.0.0"]
    resources:
      limits:
        cpu: 500m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: my-aes-portal
  namespace: default
spec:
  selector:
    app: aes-portal-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
