# Important: do not use in production environments
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aes-sample-app
  namespace: azure-iot-operations
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aes-app-config
  namespace: azure-iot-operations
data:
   broker_host: "aio-broker.azure-iot-operations.svc.cluster.local"
   broker_port: "18885"
   cert_path: "/var/run/certs/ca.crt"
   db_host: "my-redis.redis.svc.cluster.local"
   db_port: "6379"
---
apiVersion: v1
kind: Pod
metadata:
  name: aes-sample-app
  namespace: azure-iot-operations
spec:
  serviceAccountName: aes-sample-app
  containers:
  - image: capzacr.azurecr.io/sample_app:latest
    imagePullPolicy: Always
    name: aes-sample-app
    envFrom:
      - configMapRef: {name: aes-app-config}
    command: ["python3"]
    args: ["sampleapp.py", "--configmap"]
    resources:
      limits:
        cpu: 500m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi
    volumeMounts:
    - name: trust-bundle
      mountPath: /var/run/certs
  volumes:
  - name: trust-bundle
    configMap:
      name: azure-iot-operations-aio-ca-trust-bundle # Default root CA cert
